services:
  hoploy:
    build:
      context: .
    image: hoploy:latest
    ports:
      - "8102:8100"
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    volumes:
      - dataset-data:/app/datasets
      - checkpoint-data:/app/checkpoints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]

volumes:
  dataset-data:
  checkpoint-data: