wrapper:
  pearlm:
    name: pearlm
    device: "cpu"
    hopwise_checkpoint_file: ""
    dataset: "default" 
    compile_mode: "default"
  kgglm:
    name: kgglm
    device: "cpu"
    hopwise_checkpoint_file: ""
    diversity_factor: 0.3
    propagate_connected_entities: false 
    compile_mode: "default"
    recommendation_count: 5
    train_stage: "pretrain"

logits_processors:
  default:
    name: default_logits_processor
    repetition_penalty: 1.2
    no_repeat_ngram_size: 3

sequence_processor:
  default:
    name: default_cumulative_sequence_processor

logging:
  level: "DEBUG"
  format: "%(levelname_c)-9s %(message)s"